apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-app-openshift
  title: test-app-openshift
  annotations:
    janus-idp.io/tekton: test-app-openshift
    tektonci/build-namespace: poc-ktools
    github.com/project-slug: piomin/test-app-openshift
    sonarqube.org/project-key: piomin_test-app-openshift
    backstage.io/kubernetes-id: test-app-openshift
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: test-app-openshift
    prometheus.io/rule: container_memory_usage_bytes{pod=~"test-app-openshift-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"test-app-openshift-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - argocd
    - renovate
    - sonarqube
spec:
  type: service
  owner: piomin
  lifecycle: experimental