site_name: test-app-openshift
site_description: 
repo_url: https://github.com/piomin/test-app-openshift
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - test-app-openshift Documentation: index.md