apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: test-app-openshift
build:
  artifacts:
    - image: piomin/test-app-openshift
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}